services:
  postgres:
    image: postgres:16
    container_name: agentic_nl_sql_postgres

    environment:
      POSTGRES_DB: nl_to_sql
      POSTGRES_USER: nl_to_sql_admin
      POSTGRES_PASSWORD: local_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: